"""Apply latest schema changes

Revision ID: 81a408e504ad
Revises: 
Create Date: 2025-12-14 10:27:18.174662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81a408e504ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice',
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('question_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('user_emails', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('practice_id')
    )
    op.create_table('test_session',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('overall_points', sa.Float(), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.Column('started_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['practice_id'], ['practice.practice_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.drop_table('started_test')
    op.add_column('user_answers', sa.Column('session_id', sa.UUID(), nullable=True))
    op.add_column('user_answers', sa.Column('points_awarded', sa.Float(), nullable=True))
    op.alter_column('user_answers', 'user_answer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_answers', 'is_correct',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(op.f('user_answers_user_id_fkey'), 'user_answers', type_='foreignkey')
    op.create_foreign_key(None, 'user_answers', 'test_session', ['session_id'], ['session_id'])
    op.drop_column('user_answers', 'user_id')
    op.drop_column('user_answers', 'score_awarded')
    op.drop_column('user_answers', 'answered_at')
    op.alter_column('user_questions', 'options',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_questions', 'options',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.add_column('user_answers', sa.Column('answered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user_answers', sa.Column('score_awarded', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('user_answers', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_answers', type_='foreignkey')
    op.create_foreign_key(op.f('user_answers_user_id_fkey'), 'user_answers', 'users', ['user_id'], ['id'])
    op.alter_column('user_answers', 'is_correct',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user_answers', 'user_answer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user_answers', 'points_awarded')
    op.drop_column('user_answers', 'session_id')
    op.create_table('started_test',
    sa.Column('test_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('owner', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deadline', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('current_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['companies.id'], name=op.f('started_test_owner_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('started_test_user_id_fkey')),
    sa.PrimaryKeyConstraint('test_id', name=op.f('started_test_pkey'))
    )
    op.drop_table('test_session')
    op.drop_table('practice')
    # ### end Alembic commands ###
